### ISSUE TITLE
Create database 

### ISSUE THREAD

**Issue by WendyMunmunWang** [WendyMunmunWang/ERWaitingTime#11]
Oracle or MySQL??

**Comment by richard-chiang** [comment]
Vital(oxygen_saturation:REAL, temperature:REAL, blood_pressure:Real,pulse:Integer, respiration:Integer, vid:Integer)
Primary Key: vid
vid is an unique id integer assigned to the vital table after the data has been taken
This table is already in BCNF form based on FD1, vid is the superkey and from vid we can get all the attributes in this table.

Report(rid:Integer, diagnosis:Char(300), date:TimeStamp, vid:Integer, pid:Integer)
Primary Key: rid
Foreign Key: vid references Vital, pid references Patient
This table is already in BCNF form based on FD2, rid is the superkey and from rid we can get all the attributes in this table.

Prescription(pname:Char(30), amount:Real, rid:Integer)
Primary Key: pname, rid
Foreign Key: rid references Report
This table is already in BCNF form based on FD3, {pname, rid} is the superkey and from {pname, rid} we can get all the attributes in this table.

Symptom(sname:Char(30),rid:Integer)
Primary Key: sname, rid
Foreign Key: rid references Report

Staff(specialization:Char(50),years_of_experience:Integer, sid:Integer, isDoctor:Integer)v  
Primary Key: sid
This table is already in BCNF form based on FD4, sid is the superkey and from sid we can get all the attributes in this table.

Equipment(eid: Integer,type: Char(20), room: Integer)
Primary Key: eid
This table is already in BCNF form based on FD5, eid is the superkey and from eid we can get all the attributes in this table.

Patient(gender: Char(6),pname: Char(30),pid: Integer,dob: Date)
Primary Key: pid
This table is already in BCNF form based on FD6, pid is the superkey and from pid we can get all the attributes in this table.

Write(rid: Integer, sid: Integer)
Primary Key: rid, sid
Foreign Key: rid references Report, sid references Staff

Sets(eid: Integer, sid:Integer)
Primary Key: eid, sid
Foreign Key: eid references Equipment, sid references Staff

Utilize(pid:Integer, eid:Integer)
Primary Key: eid
Foreign Key: pid references Patient, eid references Equipment

Visit(pid:Integer, sid:Integer, room:Integer, date:Integer, time:Integer)
Primary Key: pid, sid
Foreign Key: pid references Patient, sid references Staff

**Comment by WendyMunmunWang** [comment]
@richard-chiang were you able to make the database?
